<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXCNXy9V\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXCNXy9V/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXCNXy9V.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXCNXy9V\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXCNXy9V\App_KernelDevDebugContainer([
    'container.build_hash' => 'XCNXy9V',
    'container.build_id' => '43b403d6',
    'container.build_time' => 1620653812,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXCNXy9V');
